services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: venkat
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db

  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: venkat
      POSTGRES_PASSWORD: password
      PGDATA: /data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/pgdata
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge