services:
  postgresql:
    container_name: order-service-postgresql
    image: postgres
    environment:
      POSTGRES_USER: venkat
      POSTGRES_PASSWORD: password
      PGDATA: /data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/pgdata
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge